# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: planiteasy
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: planiteasy
# "service" is the name of this project. This will also be added to your AWS resource names.
service: plan-it-easy

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    DYNAMODB_TABLE: EventPlansTable

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:ap-south-1:${aws:accountId}:table/EventPlansTable

resources:
  Resources:
    EventPlansTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EventPlansTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S # `id` is the primary key and is a string
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST # On-demand pricing

functions:
  addEventPlan:
    handler: src/handlers/addEvents.createEventHandler
    events:
      - httpApi:
          path: /addEvent
          method: POST
  
  getEventPlans:
    handler: src/handlers/getEvents.getEventsHandler
    events:
      - httpApi:
          path: /getEvent
          method: GET
          request:
            parameters:
              querystrings:
                limit: false
                lastkey: false

  updateEventPlans:
    handler: src/handlers/updateEvent.updateEventHandler
    events:
      - httpApi:
          path: /updateEvent
          method: PUT

  deleteEventPlan:
    handler: src/handlers/deleteEvent.deleteEventHandler
    events:
      - http:
          path: eventplan/{id}
          method: DELETE