org: planiteasy
app: planiteasy
service: plan-it-easy

custom:
  custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: 'node20'
    platform: 'node'
    external:
      - 'aws-sdk'
      - 'aws-lambda'
      - '@types/aws-lambda'
    packager: npm
  stage: ${opt:stage, 'develop'}  # Default to 'dev' if no stage is passed
  tableName: 
    develop: EventPlansTable-develop
    staging: EventPlansTable-stage
    main: EventPlansTable-prod

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    STAGE: ${self:custom.stage}  # Use the stage defined above
    DYNAMODB_TABLE: ${self:custom.tableName.${self:custom.stage}, 'EventsTable'}  # Resolves based on the stage
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:ap-south-1:${aws:accountId}:table/${self:custom.tableName.${self:custom.stage}}

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!src/**/*.ts'
    - '!.git/**'
    - '!test/**'
    - '!.vscode/**'
    - '!*.json'
    - 'dist/handlers/*.js'  
resources:
  Resources:
    EventPlansTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName.${self:custom.stage}}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  addEventPlan:
    handler: src/handlers/createEvents.createEventHandler
    events:
      - httpApi:
          path: /addEvent
          method: POST

  getEventPlans:
    handler: src/handlers/getEvents.getEventsHandler
    events:
      - httpApi:
          path: /getEvent
          method: GET

  updateEventPlans:
    handler: src/handlers/updateEvent.updateEventHandler
    events:
      - httpApi:
          path: /updateEvent
          method: PUT

  deleteEventPlan:
    handler: src/handlers/deleteEvent.deleteEventHandler
    events:
      - httpApi:
          path: /eventplan/{id}
          method: DELETE
