name: Deploy to AWS

on:
  push:
    branches:
      - develop  # deploy to dev
      - staging  # deploy to stage
      - main     # deploy to prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version

      # Step 4: Install Serverless CLI
      - name: Install Serverless CLI
        run: |
          npm install -g serverless
          serverless --version

      # Step 5: Configure AWS Credentials
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-south-1

      # Step 6: Authenticate with Serverless Framework
      - name: Serverless Framework Sign-In
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: 
          export AWS_ACCESS_KEY_ID=${{ SERVERLESS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ AWS_SECRET_ACCESS_KEY }}
          serverless login --token $AWS_ACCESS_KEY_ID

      # Step 7: Navigate to `planiteasy` directory and deploy
      - name: Deploy to AWS
        run: |
          cd planiteasy
          npm run package
