name: Deploy to AWS

on:
  push:
    branches:
      - develop  # deploys to dev
      - staging  # deploys to stage
      - main     # deploys to prod
  workflow_dispatch:  # allows manual trigger

jobs:
  deploy:
    name: Deploy with Serverless
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for using GitHub OIDC with Serverless

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd planiteasy && npm run package
      
      - name: Deploy with Serverless Framework
        uses: serverless/github-action@v3
        run: ls
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STAGE: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/staging' && 'stage' || 'dev' }}
